ref: 21723 address given report generating file name
health-connector/gluedb pull request #24
Opened 2018-02-28 20:49 UTC by prem548

2018-03-08 03:05 UTC, bill-transue approved these changes
This looks correct, should be able to find the correct file names now.

2018-03-08 16:13 UTC, Kevin-Wei requested changes

2018-03-08 16:13 UTC, Kevin-Wei commented on script/queries/steven_new.rb
> +             "CCA_#{environment_name}_enrollment_#{timestamp}.csv"
This isn't the filename in DC

2018-03-13 16:35 UTC, bill-transue approved these changes
Good job moving the report name to the `config/settings.yml` and nice spec for testing it.

2018-03-13 16:35 UTC, billy-ran-away commented on config/settings.yml
> +  enrollment_policy_report_name: "CCA_PRODUCTION_ENROLLMENT"
Nice, now it can be set to whatever.

2018-04-17 19:09 UTC, merged