adding employer demographics from incoming enrollment
health-connector/gluedb pull request #39
Opened 2018-09-25 21:30 UTC by zacharylandes

2018-10-03 19:06 UTC, bill-transue approved these changes
Updates the `EmployerEvents::EmployerImporter` to handle contacts, phones, and office locations and updates the `Employer` model to associate the new `EmployerContact` and `EmployerOfficeLocation` models where the information is stored. New specs are added for these new models and the original `EmployerImporter` spec  has been updated with the new contact elements to test the new features of the importer.

2018-10-04 15:43 UTC, TreyE requested changes
Whoops.  Employer contacts have emails.

2018-10-04 19:05 UTC, TreyE requested changes
Please see notes about nils and how glue does weird things with the phone_number column.

2018-10-04 19:05 UTC, TreyE commented on app/models/employer_events/employer_importer.rb
>        }
Sorry, this one can have nil values too - particularly dba.

2018-10-04 19:05 UTC, TreyE commented on app/models/employer_events/employer_importer.rb
> +    end
Careful here - last 4 of the phone number aren't always nil - sometimes there is an extension.

Also, glue doesn't usually even populate full phone number (!) it usually sticks that value in the "phone_number" field.  Makes perfect sense, right?

2018-10-04 19:05 UTC, TreyE commented on app/models/employer_events/employer_importer.rb
> +    end
More nil checking needed here.

2018-10-09 19:27 UTC, TreyE requested changes
One last little issue with the office locations.

2018-10-09 19:27 UTC, TreyE commented on app/models/employer_events/employer_importer.rb
> +    end
What happens if there ISN'T a phone or email for an office location?

2018-10-09 19:27 UTC, TreyE commented on app/models/employer_events/employer_importer.rb
> +    end
Ditto here, what happens if there isn't an address?

2018-10-12 15:17 UTC, TreyE approved these changes
Issues corrected.

2019-03-18 19:17 UTC, merged