ref#31437 updating haml serialization to add employer attributes(contact and OL)
health-connector/gluedb pull request #45
Opened 2018-10-02 19:55 UTC by zacharylandes

…ocations to employer

2018-10-03 18:04 UTC, TreyE requested changes
Check more carefully here.  You don't want to write out empty xml tags.

2018-10-08 18:10 UTC, bill-transue requested changes
Please update the matching spec, `spec/views/enrollment_events/policy.xml.haml_spec.rb`. Thanks!

2018-10-16 23:09 UTC, bill-transue approved these changes
This extends the `app/views/enrollment_events/_policy.xml.haml` view with two new partials, `enrollment_events/employer_with_contacts` and `enrollment_events/employer_with_office_locations`. The original policy view spec is updated to test these partials as well as new specs for the individual partials. Updates were made to the `ActionPublishHelper` to make use of the new view extensions and so its spec was updated as well. Good job!

2018-10-16 23:09 UTC, bill-transue commented on app/views/enrollment_events/_policy.xml.haml
> +        = render :partial => "enrollment_events/employer_with_contacts", :object => employer
Good job breaking these out in to partials.

2018-10-17 14:08 UTC, TreyE approved these changes

2019-05-06 17:06 UTC, TreyE commented
This has already been merged and released under a different PR.

2019-05-06 17:06 UTC, closed without merging